### ISSUE TITLE
绑定QQ时给机器人发确认绑定没有回应

### ISSUE THREAD

**Issue by XXY233** [DreamVoid/Link2QQ#3]
<strong>问题描述</strong>

绑定QQ时给机器人发确认绑定没有回应

<strong>复现方法</strong>

1. 发送确认绑定的消息

<strong>版本类型</strong>

* Minecraft 服务端版本：Paper-1.17.1
* MiraiMC 插件版本：1.4
* Link2QQ 插件版本：1.0.1

<strong>截图</strong>
![QQ截图20210911185517](https://user-images.githubusercontent.com/46647646/132945531-4d95ab8c-1928-454e-ab2e-315aab602c96.jpg)

<strong>配置文件</strong>

```
# 机器人配置
bot:
  # 启用的机器人账号
  # 只有这个账号接收到的消息才会被处理
  bot-account: 743518664

  # 启用的群号
  # 只有这个群接收到的消息才会被处理
  group-id: 1074976149

  # QQ上的绑定命令前缀
  add-bind-command: "添加绑定"

  # QQ上的确认绑定前缀
  confirm-bind-command: "确认绑定"

  # 绑定确认码长度
  confirm-code-length: 6
```
